# Generated by Django 5.0.4 on 2024-07-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='datetime_field',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
