# Generated by Django 5.0.4 on 2024-07-12 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_studentmodel_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='StudentModel_dept', to='playground.departmentmodel'),
        ),
    ]
