# Generated by Django 5.0.4 on 2024-07-12 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_studentmodel_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regd_no', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StudentModel_dept', to='playground.departmentmodel'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='regd',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentModel_regd', to='playground.registrationmodel'),
        ),
    ]
