# Generated by Django 5.0.4 on 2024-07-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_registrationmodel_alter_studentmodel_dept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_start', models.IntegerField(blank=True, null=True)),
                ('batch_end', models.IntegerField(blank=True, null=True)),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='education',
            field=models.ManyToManyField(related_name='StudentModel_education', to='playground.educationmodel'),
        ),
    ]
