# Generated by Django 5.0.7 on 2024-07-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='due_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
