student_detail=[
{"Sl_no":1	,"Roll_no":"23BCEC21"	,"Name":"ADITYESWAR  SAHU"},
{"Sl_no":2	,"Roll_no":"23BCEH78"	,"Name":"ARPIT  SARANGI"},
{"Sl_no":3	,"Roll_no":None	,"Name":"DOLAMANI  MEHER"},
{"Sl_no":4	,"Roll_no":"23BCSF77"	,"Name":"SANJANA  MOHANTA"},
{"Sl_no":5	,"Roll_no":"22BCSD02"	,"Name":"AKANKSHA  BARIK"},
{"Sl_no":6	,"Roll_no":"22BCSC85"	,"Name":"AMRIT  KUMAR"},
{"Sl_no":7	,"Roll_no":"22BCSH02"	,"Name":"ANUGRAH  GABRIEL"},
{"Sl_no":8	,"Roll_no":"22BCSD72"	,"Name":"ARPITA  BHATTA"},
{"Sl_no":9	,"Roll_no":"22BCSF82"	,"Name":"MANISH KUMAR ROUTRAY"},
{"Sl_no":10,"Roll_no":	"22BCSC11",	"Name":"PRANGYA JYOTI MOHANTY"},
{"Sl_no":11,"Roll_no":	"22BCSH93",	"Name":"PUNYASHREE  DAS"},
{"Sl_no":12,"Roll_no":	"22BECG65",	"Name":"RITUPARNA  RATH"},
{"Sl_no":13,"Roll_no":	None,	"Name":"ROUNAK   BISWAL"},
{"Sl_no":14,"Roll_no":	"22BCSI80",	"Name":"RUDRA NARAYANA SAHOO"},
{"Sl_no":15,"Roll_no":	"22BCSC66",	"Name":"SILVA  SIMRAN"},
{"Sl_no":16,"Roll_no":	"22BCSJ34",	"Name":"SOUMYA RANJAN CHAUDHURY"},
{"Sl_no":17,"Roll_no":	"22BCTC12",	"Name":"ARPITA  MANDAL"},
{"Sl_no":18,"Roll_no":	"22BCTD83",	"Name":"SHEELA  NAYAK"},
{"Sl_no":19,"Roll_no":	"22BCTC37",	"Name":"SOURAV  PRIYADARSHI"},
{"Sl_no":20,"Roll_no":	"23BEEH19",	"Name":"ANKITA APARAJITA SWAIN"},
{"Sl_no":21,"Roll_no":	"23BEEH17",	"Name":"ROSHAN  JENA"},
{"Sl_no":22,"Roll_no":	"23BEEG22",	"Name":"SUBHAM SHAW"},
{"Sl_no":23,"Roll_no":	"22BEEB85",	"Name":"DIBYA PRAKASH ROUT"},
{"Sl_no":24,"Roll_no":	"22BEEC32",	"Name":"MUKUND  SHEKHAR"},
{"Sl_no":25,"Roll_no":	"22BEEH58",	"Name":"SUJAL  PATRA"},
{"Sl_no":26,"Roll_no":	None,	"Name":"TRISHA  JANA"},
{"Sl_no":27,"Roll_no":	"23BECC36",	"Name":"SATYAJIT   SAHOO"},
{"Sl_no":28,"Roll_no":	"22BECG33",	"Name":"ARPIT KUMAR NAYAK"},
{"Sl_no":29,"Roll_no":	"22BECJ25",	"Name":"DISHANT RANJAN  SAHOO"},
{"Sl_no":30,"Roll_no":	None,	"Name":"TANAYA  DASH"},
{"Sl_no":31,"Roll_no":	"23BEII62",	"Name":"SHLOK  JHA"},
{"Sl_no":32,"Roll_no":	"22BEIG19",	"Name":"ANWESHA  MOHANTY"},
{"Sl_no":33,"Roll_no":	"22BEIC77",	"Name":"RAJASHREE   SAMANTARAY"},
{"Sl_no":34,"Roll_no":	"22BEIB70",	"Name":"SUBHALAXMI  JENA"},
{"Sl_no":35,"Roll_no":	"22BEIE04",	"Name":"TRUPTIMAYEE  SAHOO"},
{"Sl_no":36,"Roll_no":	None,	"Name":"Adarsh Nayak"}
]
